# Generated by Django 3.2.6 on 2021-08-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitorId', models.CharField(max_length=50)),
                ('hash_fingerprint', models.CharField(max_length=50)),
                ('hash_canvas_fingerprint', models.CharField(max_length=50)),
                ('user_ip', models.CharField(max_length=15)),
            ],
        ),
    ]
